name: Deploy Package to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#nobuild') }}

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist
    
    - name: Deploy package
      run: twine upload dist/* -u __token__
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
