name: Test and deploy package to PyPI

on:
  push:
    branches:
      - main

jobs:
  test-windows:
    runs-on: self-hosted
    if: ${{ !contains(github.event.head_commit.message, '#notest') }}

    steps:
    - uses: actions/checkout@v2

    - name: Install rc
      run: |
        pip install virtualenv
        python -m venv venv
        .\venv\Scripts\activate
        pip install .

    - name: Run tests (windows)
      shell: powershell
      run: |
        .\venv\Scripts\activate
        python test/test.py test/test.epp

  test-docker:
    runs-on: self-hosted
    if: ${{ !contains(github.event.head_commit.message, '#notest') }}

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      shell: powershell
      run: |
        mkdir licenses
        echo $env:ML_LIC_CONTENT > ${{github.workspace}}/licenses/matlab.lic
        echo $env:BTC_LICENSE > ${{github.workspace}}/licenses/btc.lic
        docker build -t ep-ml:24.1_23b test
      env:
        ML_LIC_CONTENT: ${{ secrets.ML_LICENSE }}
        EP_LIC_CONTENT: ${{ secrets.BTC_LICENSE }}

    - name: Run tests (docker/linux)
      run: |
        docker run --rm --mac-address 02:42:ac:11:13:37 \
            --volume "${{github.workspace}}/licenses:/licenses"
            --volume "${{github.workspace}}:${{github.workspace}}"
            --workdir "${{github.workspace}}" \
            ep-ml:24.1_23b \
            "pip install . && python test/test.py test/test.epp"

  deploy:
    needs: [test-windows, test-docker]
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#nobuild') }}

    steps:
    - uses: actions/checkout@v2
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist
    
    - name: Deploy package
      run: twine upload dist/* -u __token__
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
